use_frameworks!
platform :ios, '11.0'
inhibit_all_warnings!
target 'YPPCubeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'YPPCube', :path => '../'
  pod 'YYKeyboardManager'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
